name: pack_wise
description: Virtual Box Package.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 
  sqflite: ^2.3.2
  provider: ^6.1.1
  qr_code_scanner: ^1.0.1
  path_provider: ^2.1.2
  qr_flutter: ^4.1.0
  screenshot: ^2.1.0
  qr_image_generator: ^0.2.9
  uuid: ^4.0.0
  permission_handler: ^10.2.0
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Regular.ttf
        
 
